name: blockchain-infra

services:
  manager:
    image: hanz.dev/blockchain/manager
    env_file:
      - ./manager/.env
    volumes:
      - ./challenges:/home/ctf/challenges:ro
    ports:
      - "40000:8080"
    restart: always
  worker:
    image: hanz.dev/blockchain/worker
    env_file:
      - ./worker/.env
    restart: always
  orchestrator:
    image: hanz.dev/blockchain/orchestrator
    env_file:
      - ./orchestrator/.env
    restart: always
  forwarder:
    image: hanz.dev/blockchain/forwarder
    env_file:
      - ./forwarder/.env
    ports:
      - "40001:8080"
    restart: always
  mock-ctfd:
    image: hanz.dev/blockchain/mock-ctfd
    restart: always