name: blockchain-infra

services:
  manager:
    build:
      context: ./manager
    image: hanz.dev/blockchain/manager
    env_file:
      - ./manager/.env
    environment:
      - RPC_PUBLIC_HOST=${RPC_PUBLIC_HOST:-localhost:57254}
    volumes:
      - ./challenges:/home/ctf/challenges:ro
    ports:
      - "40000:8080"
    restart: always
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
  worker:
    build:
      context: ./worker
    image: hanz.dev/blockchain/worker
    env_file:
      - ./worker/.env
    restart: always
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
  orchestrator:
    build:
      context: ./orchestrator
    image: hanz.dev/blockchain/orchestrator
    env_file:
      - ./orchestrator/.env
    restart: always
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
  forwarder:
    build:
      context: ./forwarder
    image: hanz.dev/blockchain/forwarder
    env_file:
      - ./forwarder/.env
    ports:
      - "40001:8080"
    restart: always
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
  mock-ctfd:
    build:
      context: ./mock-ctfd
    image: hanz.dev/blockchain/mock-ctfd
    restart: always
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
  webui:
    build:
      context: ./webui
    image: hanz.dev/blockchain/webui
    ports:
      - "57254:80"
    restart: always
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL