debug: build run

build:
	go build

run:
	FLAG="HCS{test__hanzzz_%>HASH<%}" \
	CHALLENGE_NAME="test" \
	TELEGRAM_API_KEY="8355342883:AAF23EskpZxtpiTVoxIPv0j7frh02PliHiw" \
	TELEGRAM_CHAT_ID="960979575" \
	CTFD_BASE="http://localhost:9090/" \
	./manager
