debug: build run

build:
	go build

run:
	FLAG="HCS{test__hanzzz_%>HASH<%}" \
	CHALLENGE_NAME="test" \
	TELEGRAM_API_KEY="<your-telegram-api-key>" \
	TELEGRAM_CHAT_ID="<your-telegram-chat-id>" \
	CTFD_BASE="http://localhost:9090/" \
	./manager
